parser: babel-eslint
parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true
extends:
  - eslint:recommended
  - plugin:prettier/recommended
plugins:
  - flowtype
env:
  es6: true
  node: true
rules:
  curly: error
  flowtype/define-flow-type: warn
overrides:
  - files:
      - tests/*.js
    env:
      jest: true
